name: Crea Release su Jira

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Installa Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Esegui script Node.js per creare la release su Jira
        run: |
          TAG_NAME=$(git describe --tags --abbrev=0)
          JIRA_API_TOKEN=${{ secrets.JIRA_API_TOKEN }}

          echo "Creando release su Jira..."

          node - <<EOF
          const fetch = require('node-fetch');

          const TAG_NAME = process.env.TAG_NAME;
          const JIRA_API_TOKEN = process.env.JIRA_API_TOKEN;

          fetch('https://mbernardini.atlassian.net/rest/api/2/version', {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json',
              'Authorization': 'Basic ' + Buffer.from('mbernardini:' + JIRA_API_TOKEN).toString('base64')
            },
            body: JSON.stringify({ "description": "${{ env.RELEASE_VERSION }}","name": "${{ env.RELEASE_VERSION }}","archived": false,"released": true,"releaseDate": "2010-07-06","project": "QWTEST","projectId": 10001 })
          })
          .then(response => response.json())
          .then(data => {
            console.log('Release creata con successo su Jira:', data);
          })
          .catch(error => {
            console.error('Errore durante la creazione della release su Jira:', error);
            process.exit(1);
          });
          EOF
