name: Crea Release su Jira

on:
  push:
    tags:
      - '*'

env:
  JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Show env
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}

      - name: Crea Release su Jira
        run: |
          # Eseguire la richiesta API per creare una release su Jira
          curl -D- -u "matteobern92@hotmail.com:${JIRA_API_TOKEN}" -X POST -H "Content-Type: application/json" --data '{"description": "${{ env.RELEASE_VERSION }}","name": "${{ env.RELEASE_VERSION }}","archived": false,"released": true,"releaseDate": "2010-07-06","project": "QWTEST","projectId": 10001}' https://mbernardini.atlassian.net/rest/api/2/version
