name: Crea Release su Jira

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Installa Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Esegui script Node.js per creare la release su Jira
        run: |
          TAG_NAME=$(git describe --tags --abbrev=0)
          JIRA_API_TOKEN=${{ secrets.JIRA_API_TOKEN }}

          echo "Creando release su Jira..."

          node - <<EOF
          const axios = require('axios').default;

          const TAG_NAME = process.env.TAG_NAME;
          const JIRA_API_TOKEN = process.env.JIRA_API_TOKEN;

          axios.post('https://mbernardini.atlassian.net/rest/api/2/version', {
            name: TAG_NAME
          }, {
            auth: {
              username: 'username',
              password: JIRA_API_TOKEN
            },
            headers: {
              'Content-Type': 'application/json'
            }
          })
          .then(response => {
            console.log('Release creata con successo su Jira:', response.data);
          })
          .catch(error => {
            console.error('Errore durante la creazione della release su Jira:', error.response.data);
            process.exit(1);
          });
          EOF
